=== oguzcanaygun/WebServices/PatientXML/Patient.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.oguzcanaygun.com/Patient" 
xmlns:tns="http://www.oguzcanaygun.com/Patient" elementFormDefault="qualified">
	<element name="patient" type="tns:Patient"></element>
	<complexType name="Patient">
	<sequence>
		<element name="name" type="tns:String15Chars"></element>
		<element name="age" type="int"></element>
		<element name="DOB" type="date"></element>
		<element name="email" type="string"></element>
		<element name="gender" type="tns:Gender"></element>
		<element name="phone" type="string"></element>
		<element name="payment" type="tns:PaymentType"></element>
		
				
	</sequence>
	<attribute name="id" type="tns:ID"></attribute>
	</complexType>
	<complexType name="PaymentType">
		<choice>
			<element name="cash" type="int"></element>
			<element name="insuarence" type="tns:insuarence"></element>
		</choice>
	</complexType>
	
	<complexType name="insuarence">
	<all>
		<element name="provider" type="string"></element>
		<element name="limit" type="int"></element>
	</all>
	</complexType>
	
	<simpleType name="ID">
		<restriction base="int">
			<pattern value="[0-9]*"></pattern>
		</restriction>
	</simpleType>
	
	<simpleType name="String15Chars">
		<restriction base="string">
			<maxLength value="15"></maxLength>
		</restriction>
	</simpleType>
	
	<simpleType name="Gender">
		<restriction base="string">
			<enumeration value="M"></enumeration>
			<enumeration value="F"></enumeration>
		</restriction>
	</simpleType>

</schema>

=== oguzcanaygun/WebServices/PatientXML/Patient.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:patient xmlns:tns="http://www.oguzcanaygun.com/Patient" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.oguzcanaygun.com/Patient Patient.xsd " id="123">
  <tns:name>tns:name</tns:name>
  <tns:age>0</tns:age>
  <tns:DOB>2001-01-01</tns:DOB>
  <tns:email>tns:email</tns:email>
  <tns:gender>M</tns:gender>
  <tns:phone>tns:phone</tns:phone>
  <tns:payment>
    <tns:insuarence>
    <tns:provider>Blue Cross</tns:provider>
    <tns:limit>1000</tns:limit>
    </tns:insuarence>
  </tns:payment>
</tns:patient>
